In [1]:
# 1-ABC's
import numpy as np
char=np.array(["a,b,c,d,e,f,g,h,i,j"])
s=np.array(['a','b','c','d','e','f','g','h','i','j'])
print("char=",char)
print("the elements in x are of type = " ,char.dtype)
print("s has dimensions = ",s.shape)
print("s has size = ",s.size)

char= ['a,b,c,d,e,f,g,h,i,j']
the elements in x are of type =  <U17
s has dimensions =  (10,)
s has size =  10


In [3]:
# 2-Create an ndarray
f=np.linspace(2,32,16)
f=np.reshape(f,(4,4))
print("the ndarray array is = \n" ,f)

the ndarray array is = 
 [[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


In [5]:
# 3-Manipulating ndarrays
y=np.linspace(1,25,25)
y=np.reshape(y,(5,5))
odd_numbers = y[y % 2 != 0]
print("ndarray with consecutive integers is = \n",y)
print("odd numbers is = \n",odd_numbers)

ndarray with consecutive integers is = 
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
odd numbers is = 
 [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25.]
